Camera.cs
if you're not sure how to do this, please come talk to KYLE
=> Adding to my branch to do a pull request

.gitignore, Loui.cs
=> Adding my test script

Tepylo_Alek.cs
=> Added named file to test.

Stone_Brianna.cs
This script belongs to Brianna Stone
=> Added Stone_Brianna cs File

Lilly_Ftichar.cs
Just uploaded my test upload script. Checking to make sure all is done well.
=> Test script upload

CapstoneWhitebox/Assets/Scenes/Whitebox.unity, CapstoneWhitebox/Assets/Scripts/Move.cs, CapstoneWhitebox/Assets/Scripts/MovementTestScript.cs, CapstoneWhitebox/Assets/Scripts/MovementTestScript.cs.meta, CapstoneWhitebox/Assets/Scripts/TRIALCAMERASCRIPT.cs, CapstoneWhitebox/Assets/Scripts/TRIALCAMERASCRIPT.cs.meta, CapstoneWhitebox/Logs/Packages-Update.log, CapstoneWhitebox/Packages/manifest.json, CapstoneWhitebox/ProjectSettings/ProjectVersion.txt, CapstoneWhitebox/ProjectSettings/VFXManager.asset
just a basic no feature  camera, pretty much vanilla, more features made but not included in this build, will add if and when needed
=> camera stuff

CapstoneWhiteboxV1.2/Assets/Scripts/MovementTestScript.cs
Fixed some minor bugs with movement/jumping. Now controls a little better.
=> Updated movement test script

CapstoneWhiteboxV1.24/Assets/Prefabs/CyclonePlatformPlusEnemyMaster.prefab, CapstoneWhiteboxV1.24/Assets/Prefabs/CyclonePlatformPlusEnemyMaster.prefab.meta, CapstoneWhiteboxV1.24/Assets/Scripts/EnemyScripts/CycloneAttack.cs, CapstoneWhiteboxV1.24/Assets/Scripts/EnemyScripts/NextWayPoint.cs, CapstoneWhiteboxV1.24/Assets/Scripts/EnemyScripts/Pillars.cs, CapstoneWhiteboxV1.24/Assets/Scripts/EnemyScripts/Pillars.cs.meta
Enemy update remove all previous  cyclone enemy objects from scene reimport enemy script folder and add CyclonePlatformPlusMasterPrefab to scene in desired location. Made changes to CycloneEnemyAttack script made new script pillars.
=> Enemy Update

CapstoneWhiteboxV1.24/Assets/Scripts/MovementTestScript.cs
It works more like a double jump at this point, going to have to refine it to get more of a yoshi style second jump. Length of how long you can hold the jump button will also have to be limited.
=> FlutterJump Early Concept

zTargetEnemySwitch.cs
this script contains the cycle through functionality for both enemies and powerups as well as includes the Z targeting feature,  these features are as of right now  un-integrated into the main camera script but will be fully functional as of March 6, 2019.  See me (Kyle) if you have any questions as to how they can be added if you need to continue forward before I add them to the main project
=> added the script for z target and enemy cycling

LynxMaster/Assets/FBX/Player/PlayerAnimatorController.controller, LynxMaster/Assets/Prefabs/Player/Player_Alec.prefab
=> Fixes to jump and player animator

LynxMaster/Assets/Prefabs/Environment/BirdPlatform.prefab, LynxMaster/Assets/Prefabs/Environment/MultiPurposePlatform.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Interactable/Mushroom_Bounce.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Level_Prefabs/100UU_Capped_Straight_Path.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Level_Prefabs/ClimableCliff.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Platforms/Lilly_Pad.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Platforms/Moving_Long_Platform.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Platforms/Moving_Platform_Rectangle.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Platforms/Moving_Platform_Round.prefab, LynxMaster/Assets/Prefabs/Environment/TutorialPrefabs/Tree's/RedWood_Branch.prefab, LynxMaster/Assets/Scenes/Tutorial Level V1.00.unity, LynxMaster/Assets/Scripts/Environment/Bounce_Up.cs, LynxMaster/Assets/Scripts/Player/PlayerMovementv2.cs
Fixed bug where player would flutter jump instead of regular jump off the ground.
Added tags to environmental prefabs so they properly work with player movement.
Started bounce function for muchroom interactions in player script.
=> Player movement bug fixes

LynxMaster/Assets/Scenes/Tutorial_Linear_01.unity, LynxMaster/Assets/Scenes/Tutorial_Linear_01.unity.meta
adding tutorial back to scenes
=> Added linear level back

LynxMaster/Assets/Scripts/Player/PlayerComponents/MovementComponents/PlayerAirMovement.cs
Will wall jump if no input direction.
=> Wall Jump improvement

LynxMaster/Assets/Prefabs/Iteration_3/Puzzle_Prefabs/Puzzle_1.0.prefab, LynxMaster/Assets/Scenes/Map_Iteration_3.unity
Puzzle 1.0 added to newest map build.
=> Puzzle_1.0 Update

Assets/NEW_DIR/Player/Lumi_Dont_Delete_IThinkTheseAreDuplicatesButImScared/Lumi_Anims.meta, Assets/NEW_DIR/Player/Lumi_Dont_Delete_IThinkTheseAreDuplicatesButImScared/Prefab.meta, Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/PlayerAirMovement.cs, Assets/Scenes.meta
Improve ledge grab
added vertical velocity clamp in air
=> Tweeking ledge grab

Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/ToonWater/ToonWater.mat, Assets/NEW_DIR/Environment/Prefab/HealthPickUp.prefab, Assets/NEW_DIR/Environment/Prefab/HealthPickUp.prefab.meta, Assets/NEW_DIR/Player/HealthPickUp.cs, Assets/NEW_DIR/Player/HealthPickUp.cs.meta, Assets/NEW_DIR/Scenes/1_Tutorial.unity, Assets/NEW_DIR/Shader/Shader Toonv4.meta, Assets/NEW_DIR/Shader/Shader Toonv4/MultiLights.shader, Assets/NEW_DIR/Shader/Shader Toonv4/MultiLights.shader.meta, Assets/NEW_DIR/Shader/Shader Toonv4/SC_Lighting.cginc, Assets/NEW_DIR/Shader/Shader Toonv4/SC_Lighting.cginc.meta, Assets/NEW_DIR/Shader/Shader Toonv4/Toon.cginc, Assets/NEW_DIR/Shader/Shader Toonv4/Toon.cginc.meta, Assets/NEW_DIR/Shader/Shader Toonv4/ToonGUIv5.cs, Assets/NEW_DIR/Shader/Shader Toonv4/ToonGUIv5.cs.meta, Assets/NEW_DIR/Shader/Shader Toonv4/ToonV4.shader, Assets/NEW_DIR/Shader/Shader Toonv4/ToonV4.shader.meta
added new shaders to project
changed water material to transparent
=> Health pick up prefab created

Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/ToonWater/Water.cs, Assets/NEW_DIR/Environment/Prefab/TutorialPrefabs/Platforms/Moving_Platform_Rectangle.prefab, Assets/NEW_DIR/Player/Player_Lumi.prefab, Assets/NEW_DIR/Player/Script/PlayerComponents/GrappleHookController.anim, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerVariables.cs, Assets/NEW_DIR/Scenes/1_Tutorial.unity
Player now bounces straight up off enemies
Player long jump distance decreased
Dust particles turned on in scene (may need more fixing in other scenes)
Moving platform prefab in tutorial changes to make them more reliable
Moving platform placement in tutorial level changed
Changed water script to trigger better with player
=> Player and tutorial level fixes

Assets/NEW_DIR/Boss/Script.meta, Assets/NEW_DIR/Boss/Script/BossV2.cs, Assets/NEW_DIR/Boss/Script/BossV2.cs.meta, Assets/NEW_DIR/Scenes/4_Boss_New.unity
New Script BossV2 added, Boss script is no longer going to be used
=> New Script BossV2 added

Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/Level4_Prefabs/Level_Bob.anim, Assets/NEW_DIR/Environment/Prefab/Collectables/Collectable_Ice_Plant_Ring_Pop_Out(3 Shards) (1).prefab, Assets/NEW_DIR/Environment/Prefab/Collectables/Collectable_Ice_Plant_Ring_Pop_Out(3 Shards) (1).prefab.meta, Assets/NEW_DIR/Environment/Prefab/Collectables/Collectable_Ice_Plant_Ring_Pop_Out(8 Shards).prefab, Assets/NEW_DIR/Environment/Prefab/Collectables/Collectable_Ice_Plant_Ring_Pop_Out(8 Shards).prefab.meta, Assets/NEW_DIR/Player/Script/PlayerComponents/GrappleHookController.anim, Assets/NEW_DIR/Scenes/4_Level4.unity
*Added enemies and what not as well as new prefab collectables
=> level 4 ice pond

Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/PlayerAirMovement.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerClass.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs
changed ledge grab to input based jump up and drop off.
=> Ledge grab addition

Assets/NEW_DIR/Player/Anim/LedgeGrab_Idle.fbx.meta, Assets/NEW_DIR/Player/Anim/Lumi_Anims/LedgeClimb.fbx.meta, Assets/NEW_DIR/Player/Anim/PlayerAnimatorController.controller, Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/PlayerAirMovement.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerClass.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs, Assets/NEW_DIR/UI/Script/HudManager.cs
changed hud manager shard reset
=> Ledge Grab animations added

Assets/NEW_DIR/Boss/Anim/Anim_Dragon_.anim, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_.anim.meta, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Growl_1.anim, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Growl_1.anim.meta, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Growl_2.anim, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Growl_2.anim.meta, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Idle.anim, Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Idle.anim.meta, Assets/NEW_DIR/Boss/Anim/DragonHeadAnimCtrl_v2.controller, Assets/NEW_DIR/Boss/Anim/DragonHeadAnimCtrl_v2.controller.meta, Assets/NEW_DIR/Boss/Script/BossBlockingCollider.cs, Assets/NEW_DIR/Boss/Script/BossV2.cs, Assets/NEW_DIR/Scenes/5_Boss_New.unity
=> Boss Hand Code, some organization

Assets/NEW_DIR/Boss/Anim/Anim_Dragon_Head_Idle.anim, Assets/NEW_DIR/Boss/Script/BossBlockingCollider.cs, Assets/NEW_DIR/Boss/Script/BossV2.cs, Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/Script/TransitionManager.cs, Assets/NEW_DIR/Scenes/5_Boss_New.unity
Head animation keyframes added
Hand blocking set up and tested
Hands rotation and idling positions altered
Steering currently undergoing a system change
=> Changes to dragon scene, anims, and systems

Assets/Cell.meta, Assets/Cell/Materials.meta, Assets/Cell/Shaders.meta, Assets/Materials/Tutorial.meta, Assets/NEW_DIR/Scenes/3_Level3.unity, Assets/Snow.meta, Assets/Snow/Textures.meta, Assets/_A_Puzzle_Finals/Animations.meta
Ground pound sign & ice shader added to cross platforms.
=> Push for Build

Assets/NEW_DIR/Environment/Script/Killzone.cs, Assets/NEW_DIR/Player/HealthPickUp.cs
Player will not take damage from falling in kill zone immeditately after taking damage.
Health pick up will not be collected if player health is full.
=> Health and kill zone script updates

Assets/NEW_DIR/Boss/Script/BossV2.cs, Assets/NEW_DIR/Scenes/5_Boss_New.unity
- Boss hands now lerp back to position after blocking
- Boss steering range widened and breakable pillars adjusted to that range
=> Changes to BossV2 script

Assets/MoleEnemy/RockMole-Type1-Container.prefab, Assets/MoleEnemy/RockMole-Type2-Container.prefab, Assets/MoleEnemy/RockMole-Type3-Container.prefab, Assets/MoleEnemy/RockMole-Type4-Container.prefab, Assets/MoleEnemy/RockMole.cs, Assets/NEW_DIR/Environment/Prefab/TextTrigger.prefab, Assets/NEW_DIR/Player/Anim/PlayerAnimatorController.controller, Assets/NEW_DIR/Player/Particle/PS_Grapple.prefab, Assets/NEW_DIR/Player/Player_Lumi.prefab, Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/PlayerAirMovement.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerVariables.cs, Assets/NEW_DIR/Scenes/1_Tutorial.unity
Updated mole enemy script to properly turn off colliders and updated mole enemy prefabs.
Upped particle count on fireflies on player prefab.
Added more force when jumping off enemies and added animation.
Reduced collider height during jumps to better match animations.
Cleaned up some player animations and transitions.
Added collider to tutorial signs.
Added moved stuff in tutorial level.
=> Various improvements and fixes

Assets/NEW_DIR/Boss/Anim/Anim_DragonPlatSwap.anim, Assets/NEW_DIR/Boss/Anim/Anim_DragonPlatSwap.anim.meta, Assets/NEW_DIR/Boss/Anim/DragonPlat.controller, Assets/NEW_DIR/Boss/Anim/DragonPlat.controller.meta, Assets/NEW_DIR/Boss/Script/BossV2.cs, Assets/NEW_DIR/Scenes/5_Boss_New.unity
Object swap animations added for dragon platform obstacles
=> Boss Scene Update

Assets/NEW_DIR/Environment/Anim/SM_MeteoritePiece.controller, Assets/NEW_DIR/Environment/Prefab/Collectables/MeteorShardCollectable.prefab, Assets/NEW_DIR/Environment/Script/Mike/Kickable_Object.cs, Assets/NEW_DIR/Player/Lumi_Dont_Delete_IThinkTheseAreDuplicatesButImScared.meta, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs, Assets/NEW_DIR/Scenes/2_Level2.unity, Assets/PickupStuff/Tumble.cs
*Removed debug logs from player controller
*Changed enemy bounce force from 7 to 14 in line 592 of playercontrolelr.cs
*removed unneeded empty objects from collectables and switched script from collectable spin to tumble
=> Changes to collectables and kickable object

Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/Script/AnimateOnCollision.cs, Assets/NEW_DIR/Environment/Prefab/Collectables/HealthPickUp.prefab, Assets/NEW_DIR/Environment/Script/Collectables/Collectible_Spin.cs, Assets/NEW_DIR/Player/Particle/PS_Grapple.prefab, Assets/NEW_DIR/Player/Player_Lumi.prefab, Assets/NEW_DIR/Player/Script/PlayerComponents/IKScripts/RayCast_IK.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/GrappleComponent.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/MovementComponents/PlayerAirMovement.cs, Assets/NEW_DIR/Player/Script/PlayerComponents/PlayerController.cs, Assets/NEW_DIR/Scenes/1_Tutorial.unity
Changed collectable_spin script to improve performance (functionallity is the same).
player script minor changes to help improve performance.
Player prefab set up.
Setting references in tutorial level.
=> Performance improvements (hopefully)

Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/CPC_CameraPathInspector.cs, Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/EnvironmentBillBoards/Materials/Rose.mat, Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/EnvironmentBillBoards/Materials/Rose.mat.meta, Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/Final_Mat/Level_One/M_1Tree_Trunk.mat, Assets/NEW_DIR/Debug/KyleDebugFolder_GoAhead_SnoopAround/Final_Mat/Level_Two/M_2GrassCell.mat, Assets/NEW_DIR/Environment/Prefab/Collectables/HealthPickUp.prefab, Assets/NEW_DIR/Environment/Prefab/Collectables/MeteorShardCollectable.prefab, Assets/NEW_DIR/Environment/Prefab/Collectables/Moon_Shards.prefab, Assets/NEW_DIR/Player/Prefab/Player/Main Camera.prefab, Assets/NEW_DIR/Scenes/2_Level2.unity, Assets/NEW_DIR/Scenes/4_Level4.unity
*Added opening cinematic to level 2
*Alot of stuff to level two
*Changed water (PLEASE PLEASE MAKE IT BETTER)
*Added moons to level 2 (All levels now have 4 moons, why? because)
=> Cinematics and level 2 deco

Assets/NEW_DIR/Boss/Anim/CutScene_Intro.anim, Assets/NEW_DIR/Boss/OtherFiles/Lynx_Tale_Cinematic_v6.mp4.meta, Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/Script/Title.cs, Assets/NEW_DIR/Debug/LouiDebugFolder_Please_Do_Not_Alter/Script/TransitionManager.cs, Assets/NEW_DIR/Environment/Mat/New Skybox Meteor Boss.mat, Assets/NEW_DIR/Scenes/0_Title.unity, Assets/NEW_DIR/UI/Script/UIManager.cs
Added intro cinematic
Made it skippable
=> Intro Cinematic.

Assets/NEW_DIR/Player/Player_Lumi.prefab, Assets/NEW_DIR/Player/Script/PlayerComponents/FootSteps.cs
much quieter now, though kinda hard to hear over abients ounds
=> changed footsteps sounds
